{
  "uid" : "bde396e0d20c8215",
  "name" : "test_t_case008",
  "fullName" : "test_proj.test_index_3#test_t_case008",
  "historyId" : "e494c20f2411125ffa3d93b45247e426",
  "time" : {
    "start" : 1626910383135,
    "stop" : 1626910392988,
    "duration" : 9853
  },
  "status" : "broken",
  "statusMessage" : "FileNotFoundError: [Errno 2] No such file or directory: 'data/a008.txt'",
  "statusTrace" : "def test_t_case008():\n>       import test_tcA008 as tc08\n\ntest_proj/test_index_3.py:82: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n<frozen importlib._bootstrap>:1007: in _find_and_load\n    ???\n<frozen importlib._bootstrap>:986: in _find_and_load_unlocked\n    ???\n<frozen importlib._bootstrap>:680: in _load_unlocked\n    ???\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/assertion/rewrite.py:170: in exec_module\n    exec(co, module.__dict__)\ntest_proj/test_tcA008.py:45: in <module>\n    comments_text = test_comment_text()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    def test_comment_text():\n>       with open('data/a008.txt', 'r', encoding='utf-8') as file:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'data/a008.txt'\n\ntest_proj/test_tcA008.py:28: FileNotFoundError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "FileNotFoundError: [Errno 2] No such file or directory: 'data/a008.txt'",
    "statusTrace" : "def test_t_case008():\n>       import test_tcA008 as tc08\n\ntest_proj/test_index_3.py:82: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n<frozen importlib._bootstrap>:1007: in _find_and_load\n    ???\n<frozen importlib._bootstrap>:986: in _find_and_load_unlocked\n    ???\n<frozen importlib._bootstrap>:680: in _load_unlocked\n    ???\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/assertion/rewrite.py:170: in exec_module\n    exec(co, module.__dict__)\ntest_proj/test_tcA008.py:45: in <module>\n    comments_text = test_comment_text()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    def test_comment_text():\n>       with open('data/a008.txt', 'r', encoding='utf-8') as file:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'data/a008.txt'\n\ntest_proj/test_tcA008.py:28: FileNotFoundError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "849d2fa298df213f",
      "name" : "log",
      "source" : "849d2fa298df213f.txt",
      "type" : "text/plain",
      "size" : 642
    }, {
      "uid" : "5e8856971ffa21bc",
      "name" : "stderr",
      "source" : "5e8856971ffa21bc.txt",
      "type" : "text/plain",
      "size" : 435
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 2,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "test_proj"
  }, {
    "name" : "suite",
    "value" : "test_index_3"
  }, {
    "name" : "host",
    "value" : "fv-az42-193"
  }, {
    "name" : "thread",
    "value" : "3600-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test_proj.test_index_3"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 2,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 2
      },
      "items" : [ {
        "uid" : "7a6c19ad2ff6f8f4",
        "reportUrl" : "https://leeltib.github.io/conduit/1//#testresult/7a6c19ad2ff6f8f4",
        "status" : "broken",
        "statusDetails" : "FileNotFoundError: [Errno 2] No such file or directory: 'data/a008.txt'",
        "time" : {
          "start" : 1626893996937,
          "stop" : 1626894001619,
          "duration" : 4682
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "bde396e0d20c8215.json",
  "parameterValues" : [ ]
}